# Generated by Django 2.0.1 on 2018-01-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180115_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=70)),
                ('body', models.TextField()),
            ],
        ),
    ]
